max-dist-to-player: 10.0
check-delay: 1
control-item: BAMBOO
control-item-lore:
  - "Gegenstand zum Kontrollieren"
  - "deines ShulkerPets. Verwende"
  - "Rechtsklick auf dein ShulkerPet"
  - "um das Folgen zu deaktivieren."
  - "Klicke auf einen Block, um"
  - "dein ShulkerPet an diese"
  - "Position zu teleportieren."
unsafe-blocks:
  - "BEDROCK"
  - "FIRE"
  - "LAVA"
  - "WATER"
  - "VINE"
  - "STRING"

msg-prefix: "&7[&9ShulkerPet&7] "
unknown-cmd-msg: "Dieser Befehl existiert nicht."
not-your-shulkerpet-msg: "Das ist nicht dein ShulkerPet."
not-a-shulkerpet-msg: "Das ist kein ShulkerPet."
inventory-full-msg: "Dein Inventar ist voll, Befehl abgebrochen."
invalid-spawning-location-msg: "Der Versuch einen Shulker zu erzeugen ist fehlgeschlagen. Versuche es erneut in einer flachen Umgebung."
invalid-location-msg: "Das ist kein guter Platz für einen Shulker."
shulkerpet-follow-msg: "Dein ShulkerPet folgt dir."
shulkerpet-unfollow-msg: "Dein ShulkerPet folgt dir nicht mehr."
shulker-death-message: "Dein ShulkerPet ist gestorben."