max-dist-to-player: 10
check-delay: 1
control-item: BAMBOO
control-item-lore:
  - "Gegenstand zum Kontrollieren"
  - "deines ShulkerPets. Verwende"
  - "Rechtsklick auf dein ShulkerPet"
  - "um das Folgen zu deaktivieren."
  - "Klicke auf einen Block, um"
  - "deinem ShulkerPet eine bestimmte"
  - "Position zuzuweisen."
unsafe-blocks:
  - "BEDROCK"
  - "FIRE"
  - "LAVA"
  - "MAGMA"
  - "WATER"
  - "STATIONARY_WATER"
  - "SIGN"
  - "SIGN_POST"
  - "WALL_SIGN"
  - "VINE"
  - "STRING"
  - "GOLD_PLATE"
  - "IRON_PLATE"
  - "STONE_PLATE"
  - "WOOD_PLATE"
  - "FENCE_GATE"
  - "PORTAL"
  - "ENDER_PORTAL"
WrongOwner: "Das ist nicht dein ShulkerPet!"
NotAShulkerPet: "Das ist kein ShulkerPet!"

plugin-prefix: "&7[&9ShulkerPet&7] "
unknown-cmd-msg: "Dieser Befehl existiert nicht!"
not-your-shulkerpet-msg: "Das ist nicht dein ShulkerPet!"
not-a-shulkerpet-msg:
