name: ShulkerPet
version: "0.1"
api-version: "1.15"
description: "Turns a Shulker into a pet with inventory that follows you around."

author: NavyOtter
website: https://otter.navy/

main: navy.otter.shulkerpet.ShulkerPetPlugin
database: false
depend: []
softdepend: []

permissions:
  shulkerpet.create:
    description: "Creates a new ShulkerPet"
    default: true
  shulkerpet.create.egg:
    description: "Gives a SpawnEgg to create a ShulkerPet"
    default: true
  shulkerpet.pack:
    description: "Packs your ShulkerPet into an Egg"
    default: true
  shulkerpet.delete:
    description: "Removes a ShulkerPet from a Player"
    default: true
  shulkerpet.edit:
    description: "Edit an existing ShulkerPet"
    default: true
  shulkerpet.ci:
    description: "Gives the ShulkerPet Control Item"
    default: true
  shulkerpet.help:
    description: "Displays help messages"
    default: true

commands:
  shulkerpet:
    aliases: ["spet"]
